name: Publish gem to rubygems.org

on:
  workflow_dispatch:

jobs:
  release:
    uses: sue445/workflows/.github/workflows/release_gem.yml@main
    with:
      repo-name: sue445/activerecord-simple_index_name
      gem-name:  activerecord-simple_index_name
    permissions:
      contents: write
      id-token: write
